# Generated by Django 5.2.6 on 2025-10-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0004_remove_incidencia_titulo_alter_incidencia_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puesto',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='curso',
            field=models.CharField(choices=[('1ASIR', '1º ASIR'), ('2ASIR', '2º ASIR'), ('1DAM', '1º DAM'), ('2DAM', '2º DAM'), ('1DAW', '1º DAW'), ('2DAW', '2º DAW'), ('1SMR_A', '1º SMR A'), ('1SMR_B', '1º SMR B')], default='1ASIR', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
