# Generated by Django 5.2.6 on 2025-10-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0005_remove_perfilusuario_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='incidencias_asignadas',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='fixit.incidencia'),
        ),
    ]
