# Generated by Django 5.2.6 on 2025-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0006_alter_tecnico_incidencias_asignadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/'),
        ),
    ]
